baseURL = "https://imhardcore.github.io/webstack-nav/"
languageCode = "zh-cn"
title = "WebStack - 设计师网址导航"
defaultContentLanguage = "cn"

# 多语言配置
[languages]
  [languages.cn]
    weight = 1
    languageName = "Chinese"
    languagedirection = "ltr"
  [languages.en]
    weight = 2
    languageName = "English"
    languagedirection = "ltr"

# 参数配置
[params]
  description = "收集国内外优秀设计网站、UI设计资源网站、灵感创意网站"
  author = "WebStack"
  githubRepo = "imhardcore/webstack-nav"
  defaultTheme = "light"

# 输出格式
[outputs]
  home = ["HTML", "JSON"]

# Markdown 渲染
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# 隐私配置
[services]
  [services.googleAnalytics]
    ID = ""
